#__    __              __                                            __                          __
#  /  \  /  |            /  |                                          /  |                        /  |
#  $$  \ $$ |  ______   _$$ |_     ______    _______         _______  _$$ |_     ______    _______ $$ |   __
#  $$$  \$$ | /      \ / $$   |   /      \  /       |       /       |/ $$   |   /      \  /       |$$ |  /  |
#  $$$$  $$ |/$$$$$$  |$$$$$$/   /$$$$$$  |/$$$$$$$/       /$$$$$$$/ $$$$$$/    $$$$$$  |/$$$$$$$/ $$ |_/$$/
#  $$ $$ $$ |$$ |  $$ |  $$ | __ $$    $$ |$$      \       $$      \   $$ | __  /    $$ |$$ |      $$   $$<
#  $$ |$$$$ |$$ \__$$ |  $$ |/  |$$$$$$$$/  $$$$$$  |       $$$$$$  |  $$ |/  |/$$$$$$$ |$$ \_____ $$$$$$  \
#  $$ | $$$ |$$    $$/   $$  $$/ $$       |/     $$/       /     $$/   $$  $$/ $$    $$ |$$       |$$ | $$  |
#  $$/   $$/  $$$$$$/     $$$$/   $$$$$$$/ $$$$$$$/        $$$$$$$/     $$$$/   $$$$$$$/  $$$$$$$/ $$/   $$/

version: "3.7"

networks:
  notes:
    driver: bridge

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: notes-laravel8-php-fpm-80
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - nginx
    networks:
      - notes


  db:
    image: mysql:5.7.33
    build:
      context: ./docker/mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_USER: $MYSQL_USER
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - notes


  nginx:
    image: nginx:1.19.8-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 8100:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf:/etc/nginx/conf.d
    networks:
      - notes

  phpmyadmin:
    image: phpmyadmin:5.1.0-apache
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8200:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: admin_user
      PMA_PASSWORD: root1234
    networks:
      - notes
